"""Added video_path to AlarmEvent model

Revision ID: 2112c43ff936
Revises: 5d5b058cd6e0
Create Date: 2025-05-10 20:22:59.743416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2112c43ff936'
down_revision = '5d5b058cd6e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_column('video_path')

    # ### end Alembic commands ###
