"""Added TelegramVerificationCode model

Revision ID: 52ebd687fdd7
Revises: 8b66d7862b4e
Create Date: 2025-05-08 14:33:13.048631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ebd687fdd7'
down_revision = '8b66d7862b4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_verification_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_verification_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_verification_codes_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_telegram_verification_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telegram_verification_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_verification_codes_user_id'))
        batch_op.drop_index(batch_op.f('ix_telegram_verification_codes_code'))

    op.drop_table('telegram_verification_codes')
    # ### end Alembic commands ###
