"""Added notification preferences to User model with server_default

Revision ID: 5d5b058cd6e0
Revises: 52ebd687fdd7
Create Date: 2025-05-09 23:24:33.650060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d5b058cd6e0'
down_revision = '52ebd687fdd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notify_telegram_movement', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('notify_telegram_disappearance', sa.Boolean(), server_default=sa.text('1'), nullable=False))
        batch_op.add_column(sa.Column('notify_push_movement', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('notify_push_disappearance', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('notify_push_disappearance')
        batch_op.drop_column('notify_push_movement')
        batch_op.drop_column('notify_telegram_disappearance')
        batch_op.drop_column('notify_telegram_movement')

    # ### end Alembic commands ###
